### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by maxailloud** [claroline/SurveyBundle#8]
When installing the plugin (update command) I've got this issue:
 > PHP Notice:  Undefined index: Claroline\SurveyBundle\ClarolineSurveyBundle in /data/www/clarolineconnect/claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Installation/OperationExecutor.php on line 79

**Comment by anis-marrouchi** [comment]
Hi there,

I would like to test your surveyBundle, to be used on a project that i'm working. Is this bundle production ready?
Any installation instructions/ dependencies?
